# Generated by Django 6.0.5 on 2026-06-01 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='companions',
            field=models.ManyToManyField(blank=True, related_name='trips_as_companion', to=settings.AUTH_USER_MODEL),
        ),
    ]
