# Generated by Django 6.0.5 on 2026-05-26 07:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_created_by_place_is_official_place_likes_and_more'),
        ('trips', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplace',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_trip_places', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripplace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='tripplace',
            unique_together={('trip', 'place', 'day', 'order')},
        ),
    ]
