# Generated by Django 6.0.5 on 2026-06-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_initial'),
        ('trips', '0003_trip_companions'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='trips', to='places.place'),
        ),
    ]
