# Generated by Django 6.0.5 on 2026-05-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_tripphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='mood',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
