# Generated by Django 6.0.5 on 2026-06-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='places',
        ),
    ]
