# Generated by Django 6.0.5 on 2026-06-09 11:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_remove_trip_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripphoto',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
