# Generated by Django 6.0.5 on 2026-05-31 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companion',
            name='companion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_companions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_companions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='companion',
            unique_together={('user', 'companion')},
        ),
    ]
