# Generated by Django 6.0.5 on 2026-05-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_created_by_place_likes_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
