# Generated by Django 6.0.5 on 2026-05-25 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_created_by_place_is_official_place_likes_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AlterField(
            model_name='tripinvite',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_trip_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tripinvite',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_invites', to='places.place'),
        ),
        migrations.AlterField(
            model_name='tripinvite',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_trip_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tripinvite',
            unique_together={('from_user', 'to_user', 'place')},
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
