# Generated by Django 6.0.5 on 2026-05-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_avatar_remove_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companion',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=20),
        ),
    ]
