# Generated by Django 6.0.5 on 2026-05-27 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_companion_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Companion',
        ),
    ]
