# Generated by Django 6.0.5 on 2026-05-27 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_companion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Companion',
        ),
    ]
