# Generated by Django 6.0.5 on 2026-05-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_delete_companion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
